-- The Forge 脚本翻译对照表
-- 最后更新: 2024年
-- 格式: ["英文"] = "中文"

return {
    -- ========== 矿石翻译 ==========
    ["Stone"] = "石头",
    ["Sand Stone"] = "砂石",
    ["Copper"] = "铜矿",
    ["Iron"] = "铁矿",
    ["Tin"] = "锡矿",
    ["Silver"] = "银矿",
    ["Gold"] = "金矿",
    ["Mushroomith"] = "蘑菇石",
    ["Platinum"] = "铂金矿",
    ["Bananite"] = "香蕉石",
    ["Cardboardite"] = "纸板矿石",
    ["Aite"] = "不知道叫啥",
    ["Poopite"] = "粪矿",
    ["Cobalt"] = "钴矿",
    ["Titanium"] = "钛矿",
    ["Volcanic Rock"] = "火山岩",
    ["Lapis Lazuli"] = "琉璃矿",
    ["Quartz"] = "石英",
    ["Amethyst"] = "紫水晶矿石",
    ["Topaz"] = "黄玉",
    ["Diamond"] = "钻石",
    ["Sapphire"] = "蓝宝石",
    ["Cuprite"] = "杯矿",
    ["Obsidian"] = "黑曜石",
    ["Emerald"] = "翡翠",
    ["Ruby"] = "红宝石",
    ["Rivalite"] = "竞争矿石",
    ["Uranium"] = "铀矿",
    ["Myhril"] = "迈瑞尔矿石",
    ["Eye Ore"] = "猫眼矿",
    ["Fireite"] = "火焰石",
    ["Magmaite"] = "岩浆石",
    ["Lightite"] = "轻石",
    ["Demonite"] = "恶魔石",
    ["Darkryte"] = "黑石",
    ["Blue Crystal"] = "蓝水晶",
    ["Orange Crystal"] = "橙水晶",
    ["Green Crystal"] = "绿水晶",
    ["Magenta Crystal"] = "紫水晶",
    ["Crimson Crystal"] = "深红色水晶",
    
    -- ========== 敌人翻译 ==========
    ["Zombie"] = "僵尸",
    ["Delver Zombie"] = "矿工僵尸",
    ["Elite Zombie"] = "精英僵尸",
    ["Brute Zombie"] = "野蛮僵尸",
    ["Bomber"] = "爆炸骷髅",
    ["Skeleton Rogue"] = "普通骷髅",
    ["Axe Skeleton"] = "斧头骷髅",
    ["Deathaxe Skeleton"] = "死亡斧头骷髅",
    ["Elite Rogue Skeleton"] = "精英骷髅",
    ["Elite Deathaxe Skeleton"] = "精英死亡斧头骷髅",
    ["Blight Pyromancer"] = "骷髅法师",
    ["Reaper"] = "死神",
    ["Slime"] = "史莱姆",
    ["blazing"] = "火焰史莱姆",
    
    -- ========== 药水翻译 ==========
    ["HealthPotion1"] = "生命药水1",
    ["HealthPotion2"] = "生命药水2",
    ["LuckPotion1"] = "幸运药水1",
    ["MinerPotion1"] = "矿工药水1",
    ["AttackDamagePotion1"] = "伤害药水1",
    ["MovementSpeedPotion1"] = "移速药水1",
    
    -- ========== 其他矿石翻译 ==========
    ["Dark Boneite"] = "黑骨矿",
    ["Boneite"] = "骨矿",
    ["Slimite"] = "史莱姆矿",
    
    -- ========== NPC翻译 ==========
    ["Blacksmith"] = "铁匠",
    ["Merchant"] = "商人",
    ["Innkeeper"] = "旅店老板",
    ["Guard"] = "守卫",
    ["Mayor"] = "镇长",
    ["Priest"] = "牧师",
    ["Wizard"] = "巫师",
    ["Alchemist"] = "炼金术士",
    ["Tailor"] = "裁缝",
    ["Cook"] = "厨师",
    ["Fisherman"] = "渔夫",
    ["Miner"] = "矿工",
    ["Farmer"] = "农民",
    ["Hunter"] = "猎人",
    ["Knight"] = "骑士",
    ["King"] = "国王",
    ["Queen"] = "女王",
    ["Prince"] = "王子",
    ["Princess"] = "公主",
    ["Bard"] = "吟游诗人",
    
    -- ========== 商店翻译 ==========
    ["Enhancer Shop"] = "杂货店",
    ["WeaponShop"] = "武器店",
    ["ArmorShop"] = "防具店",
    ["PotionShop"] = "药水店",
    ["MagicShop"] = "魔法店",
    ["BlacksmithShop"] = "铁匠铺",
    ["AlchemyShop"] = "炼金店",
    ["ClothingStore"] = "服装店",
    ["FoodStore"] = "食品店",
    ["JewelryStore"] = "珠宝店",
    ["BookStore"] = "书店",
    ["ToolShop"] = "工具店",
    ["FurnitureStore"] = "家具店",
    ["PetShop"] = "宠物店",
    ["ToyStore"] = "玩具店",
    ["MusicStore"] = "音乐店",
    ["ArtStore"] = "艺术品店",
    ["AntiqueShop"] = "古董店",
    ["MagicItemShop"] = "魔法物品店",
    ["RareItemShop"] = "稀有物品店"
}
